/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aangsutatang.main;

import java.io.IOException;
import java.time.LocalDateTime;  // Import the LocalDateTime class
import java.time.format.DateTimeFormatter;  // Import the DateTimeFormatter class
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONObject;
import okhttp3.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import com.aangsutatang.main.assets.Client;
import java.io.BufferedReader;
import java.io.FileReader;

/**
 *
 * @author Nicolas Airel V S
 */
public class clientMainPageExchangeUI extends javax.swing.JFrame {
    
    /**
     * Creates new form mainPageUI
     */
    public clientMainPageExchangeUI() {
        initComponents();
        txtCurr1.setText("1");
        txtCurr2.setText("15615");
        
        // Welcome message
        lblWelcome.setText("Welcome! How's your day?");

        LocalDateTime myDateObj = LocalDateTime.now();
        DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String formattedDate = myDateObj.format(myFormatObj);
        lblDateTaken.setText(formattedDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        container = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        imgAppIcon = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        containerSideMenu = new com.aangsutatang.main.PanelRound();
        menuConvert = new javax.swing.JLabel();
        menuBooking = new javax.swing.JLabel();
        menuAccount = new javax.swing.JLabel();
        menuAbout = new javax.swing.JLabel();
        containerContent = new com.aangsutatang.main.PanelRound();
        containerCurr1 = new com.aangsutatang.main.PanelRound();
        txtCurr1 = new javax.swing.JTextField();
        containerCurr2 = new com.aangsutatang.main.PanelRound();
        txtCurr2 = new javax.swing.JTextField();
        containerReg1 = new com.aangsutatang.main.PanelRound();
        cmbReg1 = new javax.swing.JComboBox<>();
        containerReg2 = new com.aangsutatang.main.PanelRound();
        cmbReg2 = new javax.swing.JComboBox<>();
        containerDate = new com.aangsutatang.main.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        lblDateTaken = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnConvert = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        container.setBackground(new java.awt.Color(0, 0, 0));
        container.setFocusable(false);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aangsutatang/main/images/btn_close.png"))); // NOI18N
        btnClose.setToolTipText("Close app");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        imgAppIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aangsutatang/main/images/app_icon.png"))); // NOI18N
        imgAppIcon.setPreferredSize(new java.awt.Dimension(128, 52));

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 200, 251));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblWelcome.setText("Welcome!");

        containerSideMenu.setBackground(new java.awt.Color(0, 0, 0));
        containerSideMenu.setMinimumSize(new java.awt.Dimension(0, 0));
        containerSideMenu.setPreferredSize(new java.awt.Dimension(70, 234));
        containerSideMenu.setRoundBottomLeft(20);
        containerSideMenu.setRoundBottomRight(20);
        containerSideMenu.setRoundTopLeft(20);
        containerSideMenu.setRoundTopRight(20);

        menuConvert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aangsutatang/main/images/menu_exchange_selected.png"))); // NOI18N
        menuConvert.setPreferredSize(new java.awt.Dimension(27, 27));

        menuBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aangsutatang/main/images/menu_booking.png"))); // NOI18N
        menuBooking.setPreferredSize(new java.awt.Dimension(27, 27));
        menuBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBookingMouseClicked(evt);
            }
        });

        menuAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aangsutatang/main/images/menu_account.png"))); // NOI18N
        menuAccount.setPreferredSize(new java.awt.Dimension(27, 27));
        menuAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAccountMouseClicked(evt);
            }
        });

        menuAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aangsutatang/main/images/menu_about.png"))); // NOI18N

        javax.swing.GroupLayout containerSideMenuLayout = new javax.swing.GroupLayout(containerSideMenu);
        containerSideMenu.setLayout(containerSideMenuLayout);
        containerSideMenuLayout.setHorizontalGroup(
            containerSideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerSideMenuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(containerSideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuAbout)
                    .addComponent(menuAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuConvert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        containerSideMenuLayout.setVerticalGroup(
            containerSideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerSideMenuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(menuConvert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(menuBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(menuAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(menuAbout)
                .addGap(21, 21, 21))
        );

        containerContent.setBackground(new java.awt.Color(255, 200, 251));
        containerContent.setPreferredSize(new java.awt.Dimension(662, 234));
        containerContent.setRoundBottomLeft(20);
        containerContent.setRoundBottomRight(20);
        containerContent.setRoundTopLeft(20);
        containerContent.setRoundTopRight(20);

        containerCurr1.setBackground(new java.awt.Color(255, 157, 205));
        containerCurr1.setFocusable(false);
        containerCurr1.setPreferredSize(new java.awt.Dimension(158, 55));
        containerCurr1.setRoundBottomLeft(20);
        containerCurr1.setRoundBottomRight(20);
        containerCurr1.setRoundTopLeft(20);
        containerCurr1.setRoundTopRight(20);

        txtCurr1.setBackground(new java.awt.Color(255, 157, 205));
        txtCurr1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtCurr1.setForeground(new java.awt.Color(255, 255, 255));
        txtCurr1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCurr1.setText("txtCurr1");
        txtCurr1.setBorder(null);

        javax.swing.GroupLayout containerCurr1Layout = new javax.swing.GroupLayout(containerCurr1);
        containerCurr1.setLayout(containerCurr1Layout);
        containerCurr1Layout.setHorizontalGroup(
            containerCurr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerCurr1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCurr1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addContainerGap())
        );
        containerCurr1Layout.setVerticalGroup(
            containerCurr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerCurr1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCurr1)
                .addContainerGap())
        );

        containerCurr2.setBackground(new java.awt.Color(255, 157, 205));
        containerCurr2.setFocusable(false);
        containerCurr2.setPreferredSize(new java.awt.Dimension(158, 55));
        containerCurr2.setRoundBottomLeft(20);
        containerCurr2.setRoundBottomRight(20);
        containerCurr2.setRoundTopLeft(20);
        containerCurr2.setRoundTopRight(20);

        txtCurr2.setBackground(new java.awt.Color(255, 157, 205));
        txtCurr2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtCurr2.setForeground(new java.awt.Color(255, 255, 255));
        txtCurr2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCurr2.setText("txtCurr2");
        txtCurr2.setBorder(null);

        javax.swing.GroupLayout containerCurr2Layout = new javax.swing.GroupLayout(containerCurr2);
        containerCurr2.setLayout(containerCurr2Layout);
        containerCurr2Layout.setHorizontalGroup(
            containerCurr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerCurr2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCurr2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addContainerGap())
        );
        containerCurr2Layout.setVerticalGroup(
            containerCurr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerCurr2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCurr2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        containerReg1.setBackground(new java.awt.Color(255, 157, 205));
        containerReg1.setFocusable(false);
        containerReg1.setPreferredSize(new java.awt.Dimension(158, 55));
        containerReg1.setRoundBottomLeft(20);
        containerReg1.setRoundBottomRight(20);
        containerReg1.setRoundTopLeft(20);
        containerReg1.setRoundTopRight(20);

        cmbReg1.setBackground(new java.awt.Color(255, 157, 205));
        cmbReg1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cmbReg1.setForeground(new java.awt.Color(255, 255, 255));
        cmbReg1.setMaximumRowCount(5);
        cmbReg1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "DZD", "AOA", "ARS", "AMD", "AUD", "EUR", "AZN", "BHD", "BBD", "BYN", "EUR", "BMD", "BOB", "BAM", "BWP", "BRL", "BGN", "CVE", "KHR", "XAF", "CAD", "KYD", "XAF", "CLP", "CNY", "COP", "CDF", "XAF", "CRC", "HRK", "EUR", "CZK", "DKK", "DOP", "USD", "EGP", "USD", "XAF", "EUR", "ETB", "FJD", "EUR", "EUR", "XAF", "GEL", "EUR", "GHS", "GIP", "EUR", "DKK", "GTQ", "GBP", "GYD", "HNL", "HKD", "HUF", "ISK", "INR", "IDR", "IQD", "EUR", "IMP", "ILS", "EUR", "XOF", "JMD", "JPY", "GBP", "JOD", "KZT", "KES", "KRW", "EUR", "KWD", "KGS", "LAK", "EUR", "LBP", "LYD", "CHF", "EUR", "EUR", "MOP", "MGA", "MWK", "MYR", "MVR", "EUR", "MRU", "MUR", "MXN", "MDL", "MNT", "EUR", "MAD", "MZN", "MMK", "NAD", "EUR", "NZD", "NIO", "NGN", "MKD", "NOK", "OMR", "PKR", "ILS", "PAB", "PGK", "PYG", "PEN", "PHP", "PLN", "EUR", "USD", "QAR", "RON", "RUB", "RWF", "XCD", "SAR", "XOF", "RSD", "SGD", "EUR", "EUR", "ZAR", "EUR", "LKR", "SZL", "SEK", "CHF", "TWD", "TJS", "TZS", "THB", "USD", "TTD", "TND", "TRY", "TMT", "UGX", "UAH", "AED", "GBP", "USD", "UYU", "UZS", "VEF", "VND", "ZMW", "ZWD" }));
        cmbReg1.setSelectedIndex(35);
        cmbReg1.setToolTipText("Currency to be converted");
        cmbReg1.setBorder(null);

        javax.swing.GroupLayout containerReg1Layout = new javax.swing.GroupLayout(containerReg1);
        containerReg1.setLayout(containerReg1Layout);
        containerReg1Layout.setHorizontalGroup(
            containerReg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerReg1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbReg1, 0, 146, Short.MAX_VALUE)
                .addContainerGap())
        );
        containerReg1Layout.setVerticalGroup(
            containerReg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerReg1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbReg1)
                .addContainerGap())
        );

        containerReg2.setBackground(new java.awt.Color(255, 157, 205));
        containerReg2.setFocusable(false);
        containerReg2.setPreferredSize(new java.awt.Dimension(158, 55));
        containerReg2.setRoundBottomLeft(20);
        containerReg2.setRoundBottomRight(20);
        containerReg2.setRoundTopLeft(20);
        containerReg2.setRoundTopRight(20);

        cmbReg2.setBackground(new java.awt.Color(255, 157, 205));
        cmbReg2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cmbReg2.setForeground(new java.awt.Color(255, 255, 255));
        cmbReg2.setMaximumRowCount(5);
        cmbReg2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "DZD", "AOA", "ARS", "AMD", "AUD", "EUR", "AZN", "BHD", "BBD", "BYN", "EUR", "BMD", "BOB", "BAM", "BWP", "BRL", "BGN", "CVE", "KHR", "XAF", "CAD", "KYD", "XAF", "CLP", "CNY", "COP", "CDF", "XAF", "CRC", "HRK", "EUR", "CZK", "DKK", "DOP", "USD", "EGP", "USD", "XAF", "EUR", "ETB", "FJD", "EUR", "EUR", "XAF", "GEL", "EUR", "GHS", "GIP", "EUR", "DKK", "GTQ", "GBP", "GYD", "HNL", "HKD", "HUF", "ISK", "INR", "IDR", "IQD", "EUR", "IMP", "ILS", "EUR", "XOF", "JMD", "JPY", "GBP", "JOD", "KZT", "KES", "KRW", "EUR", "KWD", "KGS", "LAK", "EUR", "LBP", "LYD", "CHF", "EUR", "EUR", "MOP", "MGA", "MWK", "MYR", "MVR", "EUR", "MRU", "MUR", "MXN", "MDL", "MNT", "EUR", "MAD", "MZN", "MMK", "NAD", "EUR", "NZD", "NIO", "NGN", "MKD", "NOK", "OMR", "PKR", "ILS", "PAB", "PGK", "PYG", "PEN", "PHP", "PLN", "EUR", "USD", "QAR", "RON", "RUB", "RWF", "XCD", "SAR", "XOF", "RSD", "SGD", "EUR", "EUR", "ZAR", "EUR", "LKR", "SZL", "SEK", "CHF", "TWD", "TJS", "TZS", "THB", "USD", "TTD", "TND", "TRY", "TMT", "UGX", "UAH", "AED", "GBP", "USD", "UYU", "UZS", "VEF", "VND", "ZMW", "ZWD" }));
        cmbReg2.setSelectedIndex(59);
        cmbReg2.setToolTipText("Converted currency");
        cmbReg2.setBorder(null);

        javax.swing.GroupLayout containerReg2Layout = new javax.swing.GroupLayout(containerReg2);
        containerReg2.setLayout(containerReg2Layout);
        containerReg2Layout.setHorizontalGroup(
            containerReg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerReg2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbReg2, 0, 146, Short.MAX_VALUE)
                .addContainerGap())
        );
        containerReg2Layout.setVerticalGroup(
            containerReg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerReg2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbReg2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        containerDate.setBackground(new java.awt.Color(255, 157, 205));
        containerDate.setFocusable(false);
        containerDate.setPreferredSize(new java.awt.Dimension(158, 55));
        containerDate.setRoundBottomLeft(14);
        containerDate.setRoundBottomRight(14);
        containerDate.setRoundTopLeft(14);
        containerDate.setRoundTopRight(14);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aangsutatang/main/images/calendar_icon.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(18, 18));
        jLabel3.setPreferredSize(new java.awt.Dimension(18, 18));

        lblDateTaken.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDateTaken.setForeground(new java.awt.Color(255, 255, 255));
        lblDateTaken.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDateTaken.setText("date_taken");
        lblDateTaken.setMaximumSize(new java.awt.Dimension(118, 20));
        lblDateTaken.setPreferredSize(new java.awt.Dimension(118, 20));

        javax.swing.GroupLayout containerDateLayout = new javax.swing.GroupLayout(containerDate);
        containerDate.setLayout(containerDateLayout);
        containerDateLayout.setHorizontalGroup(
            containerDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerDateLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblDateTaken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        containerDateLayout.setVerticalGroup(
            containerDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerDateLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(containerDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDateTaken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 200, 251));
        jPanel1.setPreferredSize(new java.awt.Dimension(185, 185));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aangsutatang/main/images/wallet-downscaled.gif"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 185, 185));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aangsutatang/main/images/btnConvert_default.png"))); // NOI18N

        btnConvert.setBackground(new java.awt.Color(255, 146, 194));
        btnConvert.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConvert.setForeground(new java.awt.Color(255, 255, 255));
        btnConvert.setText("Convert");
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerContentLayout = new javax.swing.GroupLayout(containerContent);
        containerContent.setLayout(containerContentLayout);
        containerContentLayout.setHorizontalGroup(
            containerContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerContentLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(containerContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, containerContentLayout.createSequentialGroup()
                        .addComponent(containerDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerContentLayout.createSequentialGroup()
                        .addGroup(containerContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(containerCurr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(containerReg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addGroup(containerContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(containerReg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(containerCurr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        containerContentLayout.setVerticalGroup(
            containerContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerContentLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(containerContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(containerContentLayout.createSequentialGroup()
                        .addGroup(containerContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(containerContentLayout.createSequentialGroup()
                                .addGroup(containerContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(containerCurr2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(containerCurr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(21, 21, 21)
                                .addGroup(containerContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(containerReg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(containerReg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, containerContentLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(containerContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(containerDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConvert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(containerSideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(containerContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(imgAppIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClose)
                .addGap(19, 19, 19))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnClose)
                .addGap(14, 14, 14)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgAppIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWelcome))
                .addGap(14, 14, 14)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(containerContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(containerSideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
        // Input
        String from = cmbReg1.getSelectedItem().toString();
        String to = cmbReg2.getSelectedItem().toString();
        int amount = Integer.parseInt(txtCurr1.getText());
        LocalDateTime myDateObj = LocalDateTime.now();
        DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String date = myDateObj.format(myFormatObj);
        final String temp = "https://api.apilayer.com/exchangerates_data/convert?to=%s&from=%s&amount=%d&date=%s";
        String url = String.format(temp, to, from, amount, date);

        // Get from API
        OkHttpClient client = new OkHttpClient().newBuilder().build();

        Request request = new Request.Builder()
                .url(url)
                .addHeader("apikey", "Owi97YErgmXe4Vn0vefXTyoSFNbWxNJ9")
                .method("GET", null)
                .build();
        Response response = null;
        try {
            response = client.newCall(request).execute();
        } catch (IOException ex) {
            Logger.getLogger(clientMainPageExchangeUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        String JSON_DATA = null;
        try {
            JSON_DATA = response.body().string();
            // System.out.println(JSON_DATA);
        } catch (IOException ex) {
            Logger.getLogger(clientMainPageExchangeUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Parse information from JSON
        JSONObject json = new JSONObject(JSON_DATA);
        JSONObject query = json.getJSONObject("query");
        JSONObject info = json.getJSONObject("info");

        // Data to be retrieved
        String jsonFrom = query.getString("from");
        String jsonTo = query.getString("to");
        int jsonAmount = query.getInt("amount");
        int jsonRate = info.getInt("rate");
        String jsonDate = json.getString("date");
        int jsonResult = json.getInt("result");
        
        txtCurr2.setText(Integer.toString(jsonResult));
        lblDateTaken.setText(jsonDate);
    }//GEN-LAST:event_btnConvertActionPerformed

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void menuAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAccountMouseClicked
        clientAccountPageUI ap = new clientAccountPageUI();
        ap.show();
        this.dispose();
    }//GEN-LAST:event_menuAccountMouseClicked

    private void menuBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBookingMouseClicked
        clientBookingPageUI bp = new clientBookingPageUI();
        bp.show();
        this.dispose();
    }//GEN-LAST:event_menuBookingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientMainPageExchangeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientMainPageExchangeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientMainPageExchangeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientMainPageExchangeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientMainPageExchangeUI().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnConvert;
    private javax.swing.JComboBox<String> cmbReg1;
    private javax.swing.JComboBox<String> cmbReg2;
    private javax.swing.JPanel container;
    private com.aangsutatang.main.PanelRound containerContent;
    private com.aangsutatang.main.PanelRound containerCurr1;
    private com.aangsutatang.main.PanelRound containerCurr2;
    private com.aangsutatang.main.PanelRound containerDate;
    private com.aangsutatang.main.PanelRound containerReg1;
    private com.aangsutatang.main.PanelRound containerReg2;
    private com.aangsutatang.main.PanelRound containerSideMenu;
    private javax.swing.JLabel imgAppIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDateTaken;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel menuAbout;
    private javax.swing.JLabel menuAccount;
    private javax.swing.JLabel menuBooking;
    private javax.swing.JLabel menuConvert;
    private javax.swing.JTextField txtCurr1;
    private javax.swing.JTextField txtCurr2;
    // End of variables declaration//GEN-END:variables
}
