/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aangsutatang.main;
import java.util.ArrayList;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import com.aangsutatang.main.assets.*;
import java.awt.Color;
import java.util.Scanner;
import java.io.FileNotFoundException;

/**
 *
 * @author Nicolas Airel V S
 */
public class loginPageUI extends javax.swing.JFrame {
    static ArrayList<Client> clientList = new ArrayList<>();
    static ArrayList<Staff> staffList = new ArrayList<>();
    /**
     * Creates new form loginPageUI
     */
    
    // Methods
    public void getUserAccount(){
        try {
            // Read client account data
            File clientData = new File("clientList.txt");
            Scanner myReader = new Scanner(clientData);
            while (myReader.hasNextLine()) {
                String data = myReader.nextLine();
                String[] temp = data.split("#");
                clientList.add(new Client(temp[0], temp[1], temp[2], temp[3], temp[4]));
            }
            myReader.close();
            // Read staff account data
            File staffData = new File("staffList.txt");
            Scanner myReader2 = new Scanner(staffData);
            while (myReader2.hasNextLine()) {
                String data = myReader2.nextLine();
                String[] temp = data.split("#");
                staffList.add(new Staff(temp[0], temp[1], temp[2], temp[3], temp[4], temp[5]));
            }
            myReader2.close();
        } catch (FileNotFoundException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
    }
    
    public loginPageUI() {
        initComponents();
        getUserAccount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        containerUsername = new com.aangsutatang.main.PanelRound();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        containerPassword = new com.aangsutatang.main.PanelRound();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new com.aangsutatang.main.customButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MCC");
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setResizable(false);

        container.setBackground(new java.awt.Color(0, 0, 0));
        container.setPreferredSize(new java.awt.Dimension(315, 362));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aangsutatang/main/images/btn_close.png"))); // NOI18N
        btnClose.setToolTipText("Close app");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aangsutatang/main/images/app_icon.png"))); // NOI18N
        lblIcon.setPreferredSize(new java.awt.Dimension(88, 27));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(116, 119, 124));
        lblUsername.setText("Username");
        lblUsername.setPreferredSize(new java.awt.Dimension(45, 16));

        containerUsername.setBackground(new java.awt.Color(31, 35, 41));
        containerUsername.setPreferredSize(new java.awt.Dimension(239, 30));
        containerUsername.setRoundBottomLeft(4);
        containerUsername.setRoundBottomRight(4);
        containerUsername.setRoundTopLeft(4);
        containerUsername.setRoundTopRight(4);

        txtUsername.setBackground(new java.awt.Color(31, 35, 41));
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setBorder(null);
        txtUsername.setPreferredSize(new java.awt.Dimension(219, 14));

        javax.swing.GroupLayout containerUsernameLayout = new javax.swing.GroupLayout(containerUsername);
        containerUsername.setLayout(containerUsernameLayout);
        containerUsernameLayout.setHorizontalGroup(
            containerUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerUsernameLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        containerUsernameLayout.setVerticalGroup(
            containerUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerUsernameLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(116, 119, 124));
        lblPassword.setText("Password");
        lblPassword.setPreferredSize(new java.awt.Dimension(45, 16));

        containerPassword.setBackground(new java.awt.Color(31, 35, 41));
        containerPassword.setPreferredSize(new java.awt.Dimension(239, 30));
        containerPassword.setRoundBottomLeft(4);
        containerPassword.setRoundBottomRight(4);
        containerPassword.setRoundTopLeft(4);
        containerPassword.setRoundTopRight(4);

        txtPassword.setBackground(new java.awt.Color(31, 35, 41));
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(null);
        txtPassword.setPreferredSize(new java.awt.Dimension(219, 14));

        javax.swing.GroupLayout containerPasswordLayout = new javax.swing.GroupLayout(containerPassword);
        containerPassword.setLayout(containerPasswordLayout);
        containerPasswordLayout.setHorizontalGroup(
            containerPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPasswordLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );
        containerPasswordLayout.setVerticalGroup(
            containerPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPasswordLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        btnLogin.setBackground(new java.awt.Color(85, 146, 247));
        btnLogin.setBorder(null);
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setBorderColor(new java.awt.Color(85, 146, 247));
        btnLogin.setBorderPainted(false);
        btnLogin.setColor(new java.awt.Color(85, 146, 247));
        btnLogin.setColorClick(new java.awt.Color(85, 146, 247));
        btnLogin.setColorOver(new java.awt.Color(130, 177, 255));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogin.setPreferredSize(new java.awt.Dimension(229, 30));
        btnLogin.setRadius(4);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(containerUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(containerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(19, 19, 19))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnClose)
                .addGap(35, 35, 35)
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(containerUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(containerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        boolean isFound = false;
        int i;
        String userType = "";
        String valueOfUsername = txtUsername.getText();
        String valueOfPassword = String.valueOf(txtPassword.getPassword());
        System.out.println(valueOfUsername);
        System.out.println(valueOfPassword);
        // Search for client account
        for(i = 0 ; i < clientList.size()-1 ; i++){
            if(clientList.get(i).getUsername().equals(valueOfUsername) && clientList.get(i).getPassword().equals(valueOfPassword)){
                isFound = true;
                userType = "CLIENT";
                break;
            }
        }
        // Search for staff account
        if(!isFound){
            for(i = 0 ; i < staffList.size()-1 ; i++){
                if(staffList.get(i).getUsername().equals(valueOfUsername) && staffList.get(i).getPassword().equals(valueOfPassword)){
                    isFound = true;
                    userType = "STAFF";
                    break;
                }
            }
        }
        if(isFound){
            try{
                File file = new File("activeUser.txt");
                if(file.createNewFile()){
                    System.out.println("File created!");
                }
                else{
                    System.out.println("File already exist! Overwriting existing file");
                }
                try (FileWriter writer = new FileWriter("activeUser.txt")) {
                    if(!userType.isEmpty() && userType.equals("CLIENT")){
                        String temp = clientList.get(i).getUserId()
                                + "#" + clientList.get(i).getUserType()
                                + "#" + clientList.get(i).getName()
                                + "#" + clientList.get(i).getUsername()
                                + "#" + clientList.get(i).getPassword()
                                + "\n";
                        writer.write(temp);
                        // Open main page
                        clientMainPageExchangeUI mp = new clientMainPageExchangeUI();
                        mp.show();
                    }
                    else if(!userType.isEmpty() && userType.equals("STAFF")){
                        String temp = staffList.get(i).getUserId()
                                + "#" + staffList.get(i).getUserType()
                                + "#" + staffList.get(i).getOfficeBranch()
                                + "#" + staffList.get(i).getName()
                                + "#" + staffList.get(i).getUsername()
                                + "#" + staffList.get(i).getPassword()
                                + "\n";
                        writer.write(temp);
                        staffDashboardPageUI dp = new staffDashboardPageUI();
                        dp.show();
                    }
                    this.dispose();
                }
            }catch(IOException e){
                System.out.println("An error occurred");
            }
        }else{
            // If no account found, change color
            txtUsername.setBackground(Color.decode("#FFCCCC"));
            txtPassword.setBackground(Color.decode("#FFCCCC"));
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginPageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginPageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginPageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginPageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginPageUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private com.aangsutatang.main.customButton btnLogin;
    private javax.swing.JPanel container;
    private com.aangsutatang.main.PanelRound containerPassword;
    private com.aangsutatang.main.PanelRound containerUsername;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
